// Interface automatically generated by schemas-to-ts

import { Event } from '@strapi/database/dist/lifecycles';
  
    export interface BeforeRunEvent<TState extends Record<string, unknown>> extends Event {
      state: TState;
    }

